services:
  pg:
    image: bitnami/postgresql:latest
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brevly
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
